SELECT *
FROM D_POST_INSTALL.TEMP_CALABRIO_T_QA_CONTACTS -- 16,625 Records
;

SELECT *
FROM D_POST_INSTALL.TEMP_CALABRIO_T_QA_EVALUATIONS -- 22,730 Records
;

SELECT *
FROM D_POST_INSTALL.TEMP_CALABRIO_T_QA_EVALUATION_COMMENTS -- 130,212
;

