WITH LIST1 AS (
    SELECT CLB.CONTACT_ID
    FROM D_POST_INSTALL.T_CSLB_CALL_DATA_RAW AS CSLB
             LEFT JOIN D_POST_INSTALL.TEMP_CALABRIO_T_QA_CONTACTS AS CLB
                       ON CLB.CJP_SESSION_ID = CSLB.CALL_ID
)

   , MAIN AS (
    SELECT DISTINCT *
    FROM LIST1
    WHERE CONTACT_ID IS NOT NULL
)

SELECT *
FROM MAIN
ORDER BY 1
;